'use server';

/**
 * @fileOverview Creates legal documents based on user specifications.
 *
 * - createDocument - A function that handles the legal document creation process.
 * - DocumentCreationInput - The input type for the createDocument function.
 * - DocumentCreationOutput - The return type for the createDocument function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DocumentCreationInputSchema = z.object({
  documentType: z
    .string()
    .describe('The type of legal document to create (e.g., Simple Contract, Rental Agreement, Affidavit).'),
  details: z
    .string()
    .describe('Specific details to include in the document, such as names, dates, terms, and conditions.'),
});
export type DocumentCreationInput = z.infer<typeof DocumentCreationInputSchema>;

const DocumentCreationOutputSchema = z.object({
  documentText: z.string().describe('The full text of the generated legal document.'),
});
export type DocumentCreationOutput = z.infer<typeof DocumentCreationOutputSchema>;

export async function createDocument(input: DocumentCreationInput): Promise<DocumentCreationOutput> {
  return documentCreationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'documentCreationPrompt',
  input: {schema: DocumentCreationInputSchema},
  output: {schema: DocumentCreationOutputSchema},
  prompt: `You are an AI legal assistant. Your task is to generate a legal document based on the user's request.

Document Type: {{{documentType}}}

Details to include:
{{{details}}}

Generate the full text for the requested legal document. Ensure the document is structured professionally and includes standard legal clauses relevant to the document type.

At the end of the document, ALWAYS include the following disclaimer in bold:
**Disclaimer: This document was generated by an AI and is for informational purposes only. It is not a substitute for professional legal advice. Please consult with a qualified attorney for any legal matters.**`,
});

const documentCreationFlow = ai.defineFlow(
  {
    name: 'documentCreationFlow',
    inputSchema: DocumentCreationInputSchema,
    outputSchema: DocumentCreationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
